create extension if not exists pgcrypto;

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',phone text,created_at timestamptz not null default now());
create table public.shops(id uuid primary key default gen_random_uuid(),name text not null,owner_id uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.shop_members(shop_id uuid references public.shops(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,role text not null check(role in('owner','manager','staff')),primary key(shop_id,user_id));
create table public.categories(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,name text not null,created_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,category_id uuid references public.categories(id),name text not null,sku text,barcode text,cost_price numeric(14,2) not null default 0,sale_price numeric(14,2) not null default 0,stock_quantity numeric(14,3) not null default 0,low_stock_limit numeric(14,3) not null default 5,image_path text,updated_at timestamptz not null default now(),deleted_at timestamptz,unique(shop_id,sku));
create table public.customers(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,name text not null,phone text,address text,updated_at timestamptz not null default now(),deleted_at timestamptz);
create table public.suppliers(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,name text not null,phone text,address text,updated_at timestamptz not null default now(),deleted_at timestamptz);
create table public.sales(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,customer_id uuid references public.customers(id),total numeric(14,2) not null check(total>=0),paid numeric(14,2) not null default 0,payment_method text not null default 'cash',created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.sales(id) on delete cascade,product_id uuid not null references public.products(id),quantity numeric(14,3) not null check(quantity>0),unit_price numeric(14,2) not null,total numeric(14,2) generated always as(quantity*unit_price) stored);
create table public.purchases(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,supplier_id uuid references public.suppliers(id),total numeric(14,2) not null check(total>=0),created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.purchase_items(id uuid primary key default gen_random_uuid(),purchase_id uuid not null references public.purchases(id) on delete cascade,product_id uuid not null references public.products(id),quantity numeric(14,3) not null check(quantity>0),unit_cost numeric(14,2) not null,total numeric(14,2) generated always as(quantity*unit_cost) stored);
create table public.debts(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,customer_id uuid not null references public.customers(id),sale_id uuid references public.sales(id),amount numeric(14,2) not null check(amount>0),paid numeric(14,2) not null default 0,due_date date,created_at timestamptz not null default now(),check(paid>=0 and paid<=amount));
create table public.debt_payments(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,debt_id uuid not null references public.debts(id) on delete cascade,amount numeric(14,2) not null check(amount>0),created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.stock_movements(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,product_id uuid not null references public.products(id),movement_type text not null check(movement_type in('sale','purchase','adjustment','return')),quantity numeric(14,3) not null,reference_id uuid,created_by uuid references public.profiles(id),created_at timestamptz not null default now());

create or replace function public.is_shop_member(target_shop uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from shop_members where shop_id=target_shop and user_id=auth.uid())$$;
alter table profiles enable row level security; alter table shops enable row level security; alter table shop_members enable row level security; alter table categories enable row level security; alter table products enable row level security; alter table customers enable row level security; alter table suppliers enable row level security; alter table sales enable row level security; alter table purchases enable row level security; alter table debts enable row level security; alter table debt_payments enable row level security; alter table stock_movements enable row level security;
create policy profiles_self on profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy shops_members on shops for select using(public.is_shop_member(id));
create policy shops_owner_insert on shops for insert with check(owner_id=auth.uid());
create policy members_read on shop_members for select using(public.is_shop_member(shop_id));
create policy members_owner_write on shop_members for all using(exists(select 1 from shops s where s.id=shop_id and s.owner_id=auth.uid())) with check(exists(select 1 from shops s where s.id=shop_id and s.owner_id=auth.uid()));
do $$ declare t text; begin foreach t in array array['categories','products','customers','suppliers','sales','purchases','debts','debt_payments','stock_movements'] loop execute format('create policy %I on public.%I for all using(public.is_shop_member(shop_id)) with check(public.is_shop_member(shop_id))',t||'_members',t); end loop; end $$;

create index products_shop_idx on products(shop_id) where deleted_at is null; create index customers_shop_idx on customers(shop_id) where deleted_at is null; create index debts_customer_idx on debts(shop_id,customer_id); create index movements_product_idx on stock_movements(shop_id,product_id,created_at desc);

create view public.customer_balances with(security_invoker=true) as select c.id,c.shop_id,c.name,c.phone,coalesce(sum(d.amount-d.paid),0) balance from customers c left join debts d on d.customer_id=c.id where c.deleted_at is null group by c.id;
create view public.low_stock_products with(security_invoker=true) as select * from products where deleted_at is null and stock_quantity<=low_stock_limit;
